BASE_URL = 'http://192.168.0.107:8000/'
AUTH_ENDPOINT = BASE_URL + 'projects/verify_secret_key/'
EVENT_ACCEPT_ENDPOINT = BASE_URL + 'projects/new_log_entry/'

LEVEL_NOTSET = 0
LEVEL_DEBUG = 10
LEVEL_INFO = 20
LEVEL_WARNING = 30
LEVEL_ERROR = 40
LEVEL_CRITICAL = 50
LEVEL_FATAL = 50  # Critical and Fatal are conceptually the same

NOTSET = 'NOTSET'
DEBUG = 'DEBUG'
INFO = 'INFO'
WARNING = 'WARNING'
ERROR = 'ERROR'
CRITICAL = 'CRITICAL'
FATAL = 'FATAL'

LogEntryLevelChoices = [
    (LEVEL_NOTSET, NOTSET),
    (LEVEL_DEBUG, DEBUG),
    (LEVEL_INFO, INFO),
    (LEVEL_WARNING, WARNING),
    (LEVEL_ERROR, ERROR),
    (LEVEL_CRITICAL, CRITICAL),
    (LEVEL_FATAL, FATAL),
]

LEVEL_NAME_TO_LEVEL_VALUE_DICT = {
    NOTSET: LEVEL_NOTSET,
    DEBUG: LEVEL_DEBUG,
    WARNING: LEVEL_WARNING,
    ERROR: LEVEL_ERROR,
    INFO: LEVEL_INFO,
    FATAL: LEVEL_FATAL,
    CRITICAL: LEVEL_CRITICAL
}
